# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

os:
  - linux
  - osx

bioc_packages:
  - zlibbioc
  - Rhtslib

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - ape
  - R6
  - knitr
  - testthat

r_packages:
  - covr

# safe list
branches:
  only:
  - master
  - develop

## To deal with some packages trying to use OpenMP on macOS:
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
    mkdir -p ~/.R;
    echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars;
    echo "SHLIB_OPENMP_CFLAGS = " >>~/.R/Makevars;
    fi

after_success:
  - Rscript -e 'library(covr); codecov()'

# Because CRAN doesnâ€™t publish OSX binary packages for r-devel:
matrix:
  exclude:
  - r: devel
    os: osx
